name: CD - backend deploy homolog

on:
  push:
    paths:
      - 'back-end/**'
    branches: 
      - develop
      - main

jobs:
  back_deploy_homolog:
    if: github.ref == 'refs/heads/develop'
    name: Backend CD 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy Homolog CI back-end
        run: echo "Deployando para homolog..."

  back_deploy_prod:
    if: github.ref == 'refs/heads/main'
    name: Backend CD 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy Prod CI back-end
        run: echo "Deployando para homolog..."
