name: CD - backend deploy homolog

on:
  push:
    paths:
      - 'back-end/**'
    branches: 
      - develop

jobs:
  back_deploy_homolog:
    # if: github.event.pull_request.merged == true
    name: Backend CD 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy Homolog CI back-end
        run: echo "Deployando para homolog..."

      - name: Ver logs do container
        if: failure()
        run: docker compose logs
