name: CD - front DEPLOY homolog

on:
   push:
     paths:
       - 'front-end/**'
     branches: 
       - develop

jobs:
  front_deploy_homolog:
    if: github.ref == 'refs/heads/develop'
    name: Front Homolog CD 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy Homolog CI front-end
        run: echo "Deployando para homolog..."

  # back_deploy_prod:
  #   if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
  #   name: Backend Prod CD 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout do código
  #       uses: actions/checkout@v4

  #     - name: Deploy Prod CI back-end
  #       run: echo "Deployando para production..."

