name: CI - backend tests pull

on:
  pull_request:
    branches: 
      - develop
      - main
    paths: 
      - 'back-end/**'

jobs:
  back_end_tests_pull:
    name: Backend CI pull
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Execução CI back-end
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          docker compose -f back-end/docker-compose.ci.yml up --build --abort-on-container-exit

      - name: Ver logs do container
        if: failure()
        run: docker compose logs
  
  stub_if_no_backend_changes:
    name: Stub - Back-end sem alterações
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    # Só roda se o job principal não rodou (ou seja, sem mudanças no back-end)
    steps:
      - name: CI não necessário
        run: echo "✅ Nenhuma alteração detectada em back-end/. Liberado para merge."
