# .github/workflows/ci.yml

name: CI - Testes Automáticos

on:
  push:
    paths:
      - 'back-end/**'
    branches: [develop]
  pull_request:
    paths:
      - 'back-end/**'
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Execução CI back-end
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          docker compose -f back-end/docker-compose.ci.yml up --build --abort-on-container-exit

      - name: Ver logs do container
        if: failure()
        run: docker compose logs
