# .github/workflows/front-end-ci.yml
name: CI Frontend

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'front-end/**'

jobs:
  frontend_tests_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Executar testes front-end
        run: |
          docker compose -f front-end/docker-compose.ci.yml up --build --abort-on-container-exit

      - name: Ver logs em caso de falha
        if: failure()
        run: docker compose logs