# .github/workflows/ci.yml

name: CI - Testes Automáticos

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Ver logs do container
        if: failure()
        run: docker compose logs
